# Documentation for the shipped models ----------------------------------------
#
# All four objects are DERIVED. data-raw/ holds the scripts that rebuild them
# and records the upstream commit; each object also carries a
# `reneuro_provenance` attribute, so an .rda taken out of context can still say
# where it came from:
#
#   attr(pypsa_eur_5, "reneuro_provenance")

#' Converted PyPSA-Eur models
#'
#' Three unsolved [energyRt] models converted from PyPSA-Eur networks, spanning
#' the range this package is built for: a full European system, a small one that
#' runs in seconds, and a copperplate reference for it.
#'
#' @details
#' `pypsa_eur_41` is a 41-region European electricity system over a full year.
#' It is the realistic case, and at 12.6 MB it is by far the largest object
#' here; it is loaded lazily, so it costs nothing until touched.
#'
#' `pypsa_eur_5` is PyPSA-Eur's own Belgium example: five regions, one week
#' (168 hourly snapshots). It is small enough to solve in seconds, which makes
#' it the model every example and test uses.
#'
#' `pypsa_eur_5cp` is the same network with `transmission = "copperplate"` --
#' the same corridors, but unbounded and lossless. It is the reference point
#' for what the network representation costs: a copperplate cannot be more
#' expensive than any bounded version of itself, so it is the floor.
#'
#' `pypsa_eur_289` is the working model at continental scale. PyPSA-Eur is
#' normally clustered to 50-250 nodes for computational reasons; this sits at
#' the top of that range, aggregating the NUTS3 network to NUTS2 over the full
#' year. 296 NUTS2 regions yield 289 AC nodes: seven contain no substation of
#' their own and merge into a neighbour, **retaining their demand and
#' generation** in the cluster they join. Aggregation uses
#' `aggregate_pypsa()` -- capacities sum, intensive quantities take
#' capacity-weighted means, intra-cluster branches are dropped, and corridor
#' lengths are recomputed from cluster centroids.
#'
#' `pypsa_eur_1035` is the NUTS3 network, **experimental**, on a four-day
#' seasonal sample (96 of 8,760 hourly snapshots). It is the finest resolution
#' the data supports and is intended as the starting point for aggregation
#' work in R, rather than as a model to solve routinely. NUTS3 yields 1,035 AC
#' nodes rather than 1,477 because 442 regions contain no substation and merge
#' into neighbours; as above, their consumption is retained. Trade uses one
#' flat loss rate per corridor and a transport formulation without Kirchhoff's
#' voltage law, which is what keeps it solvable at all. It interpolates to
#' roughly 10 million parameter rows and a linear programme of 1.3 million rows
#' after presolve -- see [benchmark_solvers()] for what that costs.
#'
#' All were converted with `cost_source = "network"`, taking costs from the
#' network rather than from a separate cost assumption, so they agree with the
#' PyPSA solve they can be compared against.
#'
#' @format An [energyRt] `model` object.
#'
#' @source
#' Converted from [PyPSA-Eur](https://github.com/PyPSA/pypsa-eur) `v2026.02.0`
#' (commit `d6383eb`, PyPSA 1.1.0) by `convert_pypsa()`.
#'
#' **Licence: ODbL-1.0**, required by the share-alike terms of the
#' OpenStreetMap-derived inputs, and independent of this package's Apache-2.0
#' code licence. Attribution is required for OpenStreetMap contributors and the
#' European Environment Agency among others.
#'
#' The World Database on Protected Areas, which may not be redistributed, is
#' **not** present -- see `system.file("LICENSE.note", package = "reneuro")`
#' for how that was verified and what it costs (renewable land availability in
#' Moldova and Ukraine is overstated as a result). The same file records that
#' the OPSD and ENTSO-E demand series carry unclear upstream terms.
#'
#' Regenerated by `data-raw/make_models.R`.
#'
#' @examples
#' # Provenance travels with the object.
#' str(attr(pypsa_eur_5, "reneuro_provenance"), max.level = 1)
#' @name pypsa_eur_models
#' @aliases pypsa_eur_1035 pypsa_eur_289 pypsa_eur_41 pypsa_eur_5 pypsa_eur_5cp
NULL

#' @rdname pypsa_eur_models
"pypsa_eur_289"

#' @rdname pypsa_eur_models
"pypsa_eur_1035"

#' @rdname pypsa_eur_models
"pypsa_eur_41"

#' @rdname pypsa_eur_models
"pypsa_eur_5"

#' @rdname pypsa_eur_models
"pypsa_eur_5cp"

#' A solved Belgium scenario
#'
#' [pypsa_eur_5] interpolated and solved with GLPK. It ships so the vignettes
#' can show results without requiring a solver at build time.
#'
#' @details
#' The objective is `164664296.503735`. That figure is a regression gate rather
#' than a curiosity: `data-raw/make_be_solved.R` refuses to save a scenario that
#' does not reproduce it, so this object cannot silently drift.
#'
#' The value corresponds to the six-tranche loss default. Converting the same
#' network with `tranches = NULL` -- a single flat loss rate, rung 1 of the
#' transmission ladder -- gives `164899752.517096` instead.
#'
#' @format An [energyRt] `scenario` object with its solution attached.
#' @source Solved by `data-raw/make_be_solved.R`. Same data licence and
#'   provenance as [pypsa_eur_models].
#' @examples
#' attr(be_solved, "reneuro_provenance")$objective
"be_solved"

#' Map of the 41-region European system
#'
#' A [geoscales::geoscales] `Geoscale` for [pypsa_eur_41]: the model regions as polygons,
#' with the `sync -> country -> bus` hierarchy PyPSA-Eur clusters them by.
#'
#' @details
#' This ships **separately from the model** rather than attached to it. The
#' models are the modelling artefact and stay exactly as `convert_pypsa()`
#' produces them; the map is a convenience for looking at them. Attach it when
#' you want one:
#'
#' ```r
#' m <- setGeoscale(pypsa_eur_41, pypsa_eur_41_gs)
#' ```
#'
#' Two geoframes, coarsest first: `country` (36) and `bus` (41 model regions,
#' the atoms). Five countries — DK, ES, FR, GB, IT — are split into two buses
#' each, which is how 36 becomes 41.
#'
#' PyPSA's synchronous zones are carried as a `sync` **column**, deliberately
#' not as a geoframe. `sync` is a genuine partition of the atoms and is coarser
#' than `country` by member count (7 against 36), but it does **not nest**
#' inside it: those same five countries each straddle two zones. A geoframe
#' chain must nest — listing `sync` in it made those countries children of two
#' parents, and the spatial roll-up would then add each one's balance into both
#' zones. Group by the column, or build a separate geoscale from it, when
#' synchronous zones are what you want.
#'
#' @section The geometry is simplified:
#' The upstream onshore boundaries are 13 MB of GeoJSON. They are reduced with
#' `rmapshaper::ms_simplify(keep = 0.03, keep_shapes = TRUE)`, which drops
#' vertices while guaranteeing every polygon survives — islands included; the
#' build script refuses to save an object that lost a region.
#'
#' It is therefore a **display** geometry. Do not compute areas or distances
#' from it. Rebuild at full resolution from a PyPSA-Eur clone with
#' `pypsa_geo_layers()` and `pypsa_geoscale()` if you need those.
#'
#' No map ships for [pypsa_eur_5]; its GeoJSON sidecars are in the package
#' instead, reachable through [reneuro_example_geo()].
#'
#' @format A [geoscales::geoscales] `Geoscale` with 41 atoms and attached geometry.
#' @source Same provenance and ODbL-1.0 data licence as [pypsa_eur_models].
#'   Regenerated by `data-raw/make_geoscales.R`.
#' @examples
#' attr(pypsa_eur_41_gs, "reneuro_provenance")$simplify_keep
#' @seealso [pypsa_eur_models], [reneuro_example_geo()]
"pypsa_eur_41_gs"


#' NUTS regions of Europe, as a nested geoscale
#'
#' The administrative hierarchy PyPSA-Eur builds its regions from, as a
#' [geoscales::geoscales] `Geoscale`: **1,477 atoms** in five nested geoframes.
#'
#' @details
#' | geoframe | regions | what it is |
#' |---|---:|---|
#' | `europe` | 1 | the whole territory |
#' | `nuts0` | 36 | countries |
#' | `nuts1` | 109 | NUTS1 |
#' | `nuts2` | 296 | NUTS2 |
#' | `nuts3` | 1,477 | NUTS3 -- the atom layer |
#'
#' The single-member `europe` root exists so a **continental** commodity balance
#' has a region to live at — one Europe-wide CO2 allowance or gas market rather
#' than 36 national ones. Without it the coarsest balance available is per
#' country.
#'
#' Nesting is exact and is asserted at build time: every finer code maps to
#' exactly one coarser code. That is what lets a commodity declare
#' `@geoframe = "nuts1"` and have its balance roll up correctly from the atoms.
#'
#' @section Data carried per region:
#' The leaftable holds two families of per-region data, and the distinction
#' between them decides what each column can be used for.
#'
#' **Geographic**, from the region shapes, defined for all 1,477 atoms:
#'
#' | column | unit | kind |
#' |---|---|---|
#' | `km2` | km2, EPSG:3035 | extensive |
#' | `pop` | thousands | extensive |
#' | `gdp` | EUR per capita | **intensive** |
#' | `gdp_total` | thousand EUR | extensive |
#'
#' **Model**, from the NUTS3 network, located at substation buses:
#'
#' | column | unit | kind |
#' |---|---|---|
#' | `load_twh` | TWh per year | extensive |
#' | `peak_mw` | MW, coincident | **not additive** |
#' | `n_buses` | count of substations | extensive |
#' | `cap_mw` | MW of generation built today | extensive |
#' | `hydro_mw` | MW of that which is hydro | extensive |
#' | `pot_onwind`, `pot_solar`, `pot_solar_hsat` | MW | extensive |
#' | `pot_offwind_ac`, `pot_offwind_dc`, `pot_offwind_float` | MW | extensive |
#'
#' `gdp` looks like a total and is not: summing it gives Germany "15.6
#' million", while a population-weighted mean recovers its real ~41,800 EUR per
#' capita. `gdp_total = gdp * pop` is carried so an extensive money weight
#' exists. `peak_mw` is the maximum of the *summed* hourly series and falls
#' below the sum of its parts wherever demand is diverse; see [nuts_load].
#'
#' Seven columns are declared **weights** -- `km2`, `pop`, `gdp_total`,
#' `load_twh`, `cap_mw`, `pot_onwind`, `pot_solar` -- and `km2` is the default.
#' A weight splits a coarse quantity across atoms and averages an intensive one
#' back up, so the choice is a modelling decision: national demand should be
#' split by `load_twh` or `pop`, not by area, and a wind target by `pot_onwind`.
#' See [geoscales::recast_geoscale()].
#'
#' @section The potentials overlap and must not be summed:
#' `pot_solar` and `pot_solar_hsat` are fixed-tilt and single-axis-tracking
#' photovoltaics **on the same land**, and 313 of the 314 offshore regions carry
#' more than one `pot_offwind_*` type on the same sea area. Adding them counts
#' the same hectare twice. They are kept as separate columns so that no summing
#' rule is imposed here; the three offshore columns are excluded from the weight
#' set for a second reason -- they are zero for every landlocked country.
#'
#' @section 442 regions carry no model data:
#' PyPSA-Eur places demand, plant and potential at substation buses, and 442 of
#' the 1,477 NUTS3 regions contain none. Every model column is zero there. That
#' is the model's own allocation -- a busless region's land and load were folded
#' into the neighbour it clusters with -- and not a statement about the region.
#' The geographic columns are unaffected.
#'
#' The effect propagates upward exactly as far as the node counts do: **7 NUTS2
#' groups and 3 NUTS1 groups** contain no substation at all, and these are
#' precisely the regions lost when 296 NUTS2 become 289 nodes and 109 NUTS1
#' become 106.
#'
#' A weight summing to zero over a group divides by zero when averaging an
#' intensive quantity into it. Those groups are recorded rather than patched:
#'
#' ```r
#' attr(nuts_gs, "weight_degeneracy")
#' ```
#'
#' Two entries are degenerate for a reason other than a missing substation, and
#' both are real: `GBI3` (Inner London) has no generation and no land the
#' availability rules admit for wind, and `NO07` (Nord-Norge) has no solar
#' potential, lying above the Arctic Circle.
#'
#' @section Four countries have no NUTS:
#' **BA, MD, UA and XK** are outside the NUTS system entirely -- the same four
#' PyPSA-Eur caps at administrative level 1. They are filled from OpenStreetMap
#' `adm1` boundaries (3, 37, 27 and 7 regions respectively), which become
#' `nuts3` atoms, and the levels above them are **padded**: `MD0` at `nuts1`,
#' `MD00` at `nuts2`.
#'
#' Padding rather than repeating matters. PyPSA-Eur repeats the adm1 code at
#' every level, which makes each of those regions **its own parent**: the
#' derived region hierarchy then carries identity pairs like `(MD-BA, MD-BA)`,
#' and energyRt's spatial roll-up degenerates to
#' `vOutTot[MD-BA] = ... + vOutTot[MD-BA]`, silently forcing everything else to
#' zero.
#'
#' The padding follows Eurostat's own convention for identical geography --
#' Luxembourg is `LU -> LU0 -> LU00 -> LU000` -- and no NUTS country produces a
#' single identity pair. The honest caveat remains that "NUTS1"/"NUTS2" for
#' those four is a stand-in, not a real administrative level.
#'
#' @section A known gap in the gdp weight:
#' One region, `MD-BD` (Bender), carries `gdp = 0` in the source, and it is left
#' uncorrected -- substituting a plausible number would hide a real gap.
#'
#' It no longer breaks anything: with the levels padded, `MD-BD` sits inside
#' `MD0`/`MD00` rather than being its own parent, so no group sums to zero and
#' every weight now passes the build script's checks cleanly.
#'
#' @section The geometry is simplified:
#' Reduced from 37 MB of source GeoJSON with
#' `rmapshaper::ms_simplify(keep = 0.02, keep_shapes = TRUE)`; the build refuses
#' to save if a region is lost. It is a **display** geometry -- the `km2` weight
#' was computed from the *unsimplified* polygons in EPSG:3035, so use that
#' rather than measuring the shipped shapes.
#'
#' @format A [geoscales::geoscales] `Geoscale` with 1,477 atoms, five geoframes,
#'   14 data columns and attached geometry.
#' @source
#' Built from PyPSA-Eur's own `resources/<run>/nuts3_shapes.geojson` rather than
#' from raw Eurostat files, so the regions match the networks this package
#' converts exactly. That layer combines **Eurostat NUTS 2021** (© European
#' Union, reuse permitted with attribution) with **OpenStreetMap** adm1
#' boundaries (ODbL-1.0) for the four countries NUTS does not reach.
#'
#' The model layer comes from the NUTS3 network `base_s_1035_elec.nc` of the
#' same build, whose AC bus names are NUTS3 codes.
#'
#' See `system.file("LICENSE.note", package = "reneuro")`. Regenerated by
#' `data-raw/nuts_gs.R`.
#' @examples
#' # The hierarchy, coarsest first
#' geoscales::geoscale_geoframes(nuts_gs)
#'
#' # How many regions at each level
#' vapply(geoscales::geoscale_geoframes(nuts_gs),
#'        function(f) length(geoscales::geoscale_regions(nuts_gs, f)), 0L)
#'
#' # Demand and wind potential by country, from the atom layer
#' geoscales::geoscale_leaftable(nuts_gs) |>
#'   as.data.frame() |>
#'   dplyr::group_by(nuts0) |>
#'   dplyr::summarise(twh = sum(load_twh), wind_gw = sum(pot_onwind) / 1e3) |>
#'   dplyr::arrange(dplyr::desc(twh)) |>
#'   head()
#' @seealso [nuts_load], [pypsa_eur_41_gs], [geoscales::recast_geoscale()]
"nuts_gs"


#' Electricity demand per NUTS region
#'
#' Annual energy and coincident peak for every region of [nuts_gs], at all four
#' levels plus a Europe-wide row.
#'
#' @details
#' | column | meaning |
#' |---|---|
#' | `level` | `europe`, `nuts0`, `nuts1`, `nuts2`, `nuts3` |
#' | `region` | region code at that level |
#' | `load_twh` | annual energy, TWh — **extensive**, sums up the hierarchy |
#' | `peak_gw` | max of the **summed** hourly series, GW — *not* extensive |
#' | `n_buses` | substation buses in the region; `0` means no demand at all |
#'
#' Total across all regions is 3,356 TWh at every level.
#'
#' @section Peak diversity is zero below the country:
#' In general `peak(parent) <= sum(peak(children))`, the gap being load
#' diversity. Here it is **exactly zero within every country**, and appears only
#' across Europe (580 GW summed against 543 GW coincident, 6.8%).
#'
#' That is a property of the data, not of European demand. PyPSA-Eur builds
#' per-bus load as a static fraction times the *national* hourly series, so
#' every bus in a country carries an identical normalised shape. Going finer
#' than a country adds spatial detail to the **level** of demand and none to its
#' **shape**: at NUTS3, 1,477 regions share 36 distinct profiles.
#'
#' @section 442 regions carry no demand:
#' `load.substation_only: true` places demand only on substation buses, and 442
#' of the 1,477 NUTS3 regions contain none — Germany alone has 182. They are
#' present with `load_twh = 0` and `n_buses = 0` rather than omitted, so the gap
#' shows on a map instead of vanishing. It is a real ceiling on useful
#' resolution.
#'
#' @format A `data.frame` of 2,059 rows and 5 columns.
#' @source
#' Aggregated from PyPSA-Eur's `electricity_demand_base_s.nc` (4,356 buses ×
#' 8,760 hours). Buses are located against the **unsimplified** upstream
#' `nuts3_shapes.geojson`. Same data licence as [pypsa_eur_models].
#' Regenerated by `data-raw/make_nuts_load.R`.
#' @examples
#' # energy is extensive: every level sums to the same total
#' tapply(nuts_load$load_twh, nuts_load$level, sum)
#' @seealso [nuts_gs], [nuts_lines]
"nuts_load"

#' Transmission lines with NUTS3 endpoints
#'
#' Every AC line of PyPSA-Eur's simplified network whose two ends fall in
#' *different* NUTS3 regions, with the parameters needed to aggregate it to any
#' coarser level.
#'
#' @details
#' | column | meaning |
#' |---|---|
#' | `from`, `to` | NUTS3 codes, ordered so `from < to` |
#' | `s_nom` | thermal rating, MW — **extensive**, sums |
#' | `length_km`, `x`, `r` | as built; length and impedance are *recomputed* on aggregation |
#' | `v_nom`, `num_parallel` | voltage and circuit count |
#'
#' Deliberately **not** pre-aggregated, not even to NUTS3, so one routine can be
#' applied at all four levels and NUTS3 is not a privileged case.
#'
#' @section Over half the grid is already gone:
#' Lines with both ends in one NUTS3 region are dropped, exactly as
#' `pypsa.clustering.spatial.aggregatelines()` drops intra-cluster lines. That
#' is **4,218 of 7,360 lines (57%), carrying 53% of capacity** — discarded at
#' the *finest* level available. Coarsening further only removes more.
#'
#' @section Aggregating correctly:
#' Three different rules, none of them a plain average:
#'
#' * `s_nom`, `num_parallel` — **sum**;
#' * `length` — **recomputed** as the great-circle distance between the two
#'   region centroids times `line_length_factor` (1.25). It is not inherited, and
#'   it *grows*: median corridor length rises from 85 km at NUTS3 to 459 km at
#'   NUTS0;
#' * `x`, `r` — rescaled by the length ratio, then **parallel-combined** as
#'   `1 / sum(1/x)`.
#'
#' Because impedance follows length, losses are **overestimated** at coarse
#' levels; because `s_nom` is a plain thermal sum ignoring N-1 and loop flows,
#' capacity is **overestimated** too. The two do not cancel.
#'
#' @format A `data.frame` of 3,142 rows and 8 columns.
#' @source
#' PyPSA-Eur `base_s.nc` (7,360 lines, 4,382 buses), endpoints located against
#' the unsimplified `nuts3_shapes.geojson`. Same data licence as
#' [pypsa_eur_models]. Regenerated by `data-raw/make_nuts_lines.R`.
#' @examples
#' # how much of the network never crosses a NUTS3 boundary
#' p <- attr(nuts_lines, "reneuro_provenance")
#' c(total = p$lines_total, dropped = p$lines_intra_dropped)
#' @seealso [nuts_gs], [nuts_load]
"nuts_lines"
